project 'EatFit.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'EatFit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EatFit
  pod 'R.swift'
  pod 'Cartography'
  pod 'SwiftFormat/CLI'
  pod 'microLogger'

  target 'EatFitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
