project 'EatFit.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'EatFit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EatFit
  pod 'R.swift', '~> 4.0.0'
  pod 'Cartography', '~> 3.0.2'
  pod 'SwiftFormat/CLI', '~> 0.33.7'
  pod 'microLogger', '~> 1.0.2'

  target 'EatFitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
